In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
x1 = pd.read_csv("PastSub\subrf1.csv")
x1

       Unnamed: 0  countyFIPS  stateFIPS        date  Confirmed_cases
0               1        1001          1  01-02-2021           500.86
1               2        1003          1  01-02-2021          2016.47
2               3        1005          1  01-02-2021           191.88
3               4        1007          1  01-02-2021           117.84
4               5        1009          1  01-02-2021           462.46
...           ...         ...        ...         ...              ...
47125       47126       56037         56  15-02-2021            57.50
47126       47127       56039         56  15-02-2021           109.51
47127       47128       56041         56  15-02-2021            58.43
47128       47129       56043         56  15-02-2021            58.42
47129       47130       56045         56  15-02-2021            58.18

[47130 rows x 5 columns]

In [2]:
x2 = pd.read_csv("MeanImputedNotScaled_dated.csv")
x2

,DOMESTIC_Flights_Cnt,INTERNATIONAL_Flights_Cnt,INTERNATIONAL_Air_Passengers,DOMESTIC_Air_Passengers,apple_mobility_driving,google_mobility_workplaces,Electricity_Sales_ Customers_Count_Transportation,Electricity_Sales_ Customers_Count_Industrial,Electricity_Sales_ Revenue_Transportation ($ x1000),Electricity_Sales_ Sales_Transportation (MWHr),...,C_HispanicPCT,C_PCTPOVALL_2019,C_PCTPOV017_2019,C_PCTPOV517_2019,C_MEDHHINC_2019,deaths,stateFIPS,confirmed_cases,countyFIPS,date
0,10925.018692,682.528037,50595.607477,588759.504673,101.510000,-23.15808,0.000000,16298.000000,0.000000,0.000000,...,0.0257,12.1,15.9,14.4,58233.0,0.0,1.0,0.0,1001.0,2020-01-22
1,10925.018692,682.528037,50595.607477,588759.504673,103.120000,-23.15808,0.000000,16298.000000,0.000000,0.000000,...,0.0458,10.1,13.5,13.3,59871.0,0.0,1.0,0.0,1003.0,2020-01-22
2,10925.018692,682.528037,50595.607477,588759.504673,120.670000,-23.15808,0.000000,16298.000000,0.000000,0.000000,...,0.0509,27.1,41.0,39.5,35972.0,0.0,1.0,0.0,1005.0,2020-01-22
3,10925.018692,682.528037,50595.607477,588759.504673,111.180000,-23.15808,0.000000,16298.000000,0.000000,0.000000,...,0.0204,20.3,25.9,25.2,47918.0,0.0,1.0,0.0,1007.0,2020-01-22
4,10925.018692,682.528037,50595.607477,588759.504673,91.560000,-23.15808,0.000000,16298.000000,0.000000,0.000000,...,0.0860,16.3,21.0,21.4,52902.0,0.0,1.0,0.0,1009.0,2020-01-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1179370,10925.018692,682.528037,50595.607477,588759.504673,161.130000,-23.15808,3.231321,72386.890999,2019.507886,21366.056357,...,0.1584,8.3,10.1,8.2,80639.0,32.0,56.0,3472.0,56037.0,2021-01-30
1179371,10925.018692,682.528037,50595.607477,588759.504673,171.600000,-23.15808,3.231321,72386.890999,2019.507886,21366.056357,...,0.1560,6.0,5.7,4.7,98837.0,6.0,56.0,3078.0,56039.0,2021-01-30
1179372,10925.018692,682.528037,50595.607477,588759.504673,148.020000,-23.15808,3.231321,72386.890999,2019.507886,21366.056357,...,0.0906,8.5,9.6,7.8,70756.0,12.0,56.0,1960.0,56041.0,2021-01-30
1179373,10925.018692,682.528037,50595.607477,588759.504673,142.338662,-23.15808,3.231321,72386.890999,2019.507886,21366.056357,...,0.1400,11.1,13.9,12.3,55122.0,25.0,56.0,864.0,56043.0,2021-01-30
1179374,10925.018692,682.528037,50595.607477,588759.504673,142.338662,-23.15808,3.231321,72386.890999,2019.507886,21366.056357,...,0.0361,10.5,13.8,11.8,59410.0,4.0,56.0,610.0,56045.0,2021-01-30

In [4]:
x2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1179375 entries, 0 to 1179374
Data columns (total 63 columns):
 #   Column                                                                  Non-Null Count    Dtype
---  ------                                                                  --------------    -----
 0   DOMESTIC_Flights_Cnt                                                    1179375 non-null  float64
 1   INTERNATIONAL_Flights_Cnt                                               1179375 non-null  float64
 2   INTERNATIONAL_Air_Passengers                                            1179375 non-null  float64
 3   DOMESTIC_Air_Passengers                                                 1179375 non-null  float64
 4   apple_mobility_driving                                                  1179375 non-null  float64
 5   google_mobility_workplaces                                              1179375 non-null  float64
 6   Electricity_Sales_ Customers_Count_Transportation                       1179375 non-null  float64
 7   Electricity_Sales_ Customers_Count_Industrial                           1179375 non-null  float64
 8   Electricity_Sales_ Revenue_Transportation ($ x1000)                     1179375 non-null  float64
 9   Electricity_Sales_ Sales_Transportation (MWHr)                          1179375 non-null  float64
 10  Electricity_Sales_ Customers_Count_Residential                          1179375 non-null  float64
 11  Electricity_Sales_ Revenue_Commercial ($ x1000)                         1179375 non-null  float64
 12  Electricity_Sales_ Customers_Count_Commercial                           1179375 non-null  float64
 13  Electricity_Sales_ Sales_Commercial (MWHr)                              1179375 non-null  float64
 14  Electricity_Sales_ Revenue_Residential ($ x1000)                        1179375 non-null  float64
 15  Electricity_Sales_ Sales_Residential (MWHr)                             1179375 non-null  float64
 16  Electricity_Sales_ Sales_Industrial (MWHr)                              1179375 non-null  float64
 17  Electricity_Sales_ Revenue_Industrial ($ x1000)                         1179375 non-null  float64
 18  previous_day_admission_pediatric_covid_suspected_SD                     1179375 non-null  float64
 19  staffed_adult_icu_bed_occupancy_SD                                      1179375 non-null  float64
 20  inpatient_bed_covid_utilization_SD                                      1179375 non-null  float64
 21  percent_of_inpatients_with_covid_SD                                     1179375 non-null  float64
 22  inpatient_beds_utilization_denominator_SD                               1179375 non-null  float64
 23  inpatient_beds_utilization_numerator_SD                                 1179375 non-null  float64
 24  inpatient_beds_utilization_SD                                           1179375 non-null  float64
 25  total_pediatric_patients_hospitalized_confirmed_covid_SD                1179375 non-null  float64
 26  total_pediatric_patients_hospitalized_confirmed_and_suspected_covid_SD  1179375 non-null  float64
 27  total_adult_patients_hospitalized_confirmed_covid_SD                    1179375 non-null  float64
 28  total_adult_patients_hospitalized_confirmed_and_suspected_covid_SD      1179375 non-null  float64
 29  staffed_icu_adult_patients_confirmed_covid_SD                           1179375 non-null  float64
 30  staffed_icu_adult_patients_confirmed_and_suspected_covid_SD             1179375 non-null  float64
 31  staffed_adult_icu_bed_occupancy_coverage_SD                             1179375 non-null  float64
 32  adult_icu_bed_utilization_SD                                            1179375 non-null  float64
 33  previous_day_admission_pediatric_covid_confirmed_SD                     1179375 non-null  float64
 34  previous_day_admission_adult_covid_suspected_SD                         1179375 non-null  float64
 35  previous_day_admission_adult_covid_confirmed_SD                         1179375 non-null  float64
 36  inpatient_beds_coverage_SD                                              1179375 non-null  float64
 37  adult_icu_bed_covid_utilization_SD                                      1179375 non-null  float64
 38  inpatient_beds_SD                                                       1179375 non-null  float64
 39  hospital_onset_covid_coverage_SD                                        1179375 non-null  float64
 40  hospital_onset_covid_SD                                                 1179375 non-null  float64
 41  critical_staffing_shortage_anticipated_within_week_yes_SD               1179375 non-null  float64
 42  critical_staffing_shortage_today_yes_SD                                 1179375 non-null  float64
 43  C_M_Employed_corr                                                       1179375 non-null  float64
 44  C_M_Labour_Force_corr                                                   1179375 non-null  float64
 45  C_M_Unemployment_Rate_corr                                              1179375 non-null  float64
 46  C_TOT_MALE                                                              1179375 non-null  float64
 47  C_WA_MALE                                                               1179375 non-null  float64
 48  C_TOT_POP                                                               1179375 non-null  float64
 49  C_TOT_FEMALE                                                            1179375 non-null  float64
 50  C_WA_FEMALE                                                             1179375 non-null  float64
 51  C_MinorityPCT                                                           1179375 non-null  float64
 52  C_BlackPCT                                                              1179375 non-null  float64
 53  C_HispanicPCT                                                           1179375 non-null  float64
 54  C_PCTPOVALL_2019                                                        1179375 non-null  float64
 55  C_PCTPOV017_2019                                                        1179375 non-null  float64
 56  C_PCTPOV517_2019                                                        1179375 non-null  float64
 57  C_MEDHHINC_2019                                                         1179375 non-null  float64
 58  deaths                                                                  1179375 non-null  float64
 59  stateFIPS                                                               1179375 non-null  float64
 60  confirmed_cases                                                         1179375 non-null  float64
 61  countyFIPS                                                              1179375 non-null  float64
 62  date                                                                    1179375 non-null  object
dtypes: float64(62), object(1)
memory usage: 566.9+ MB

In [5]:
corr_matrix = x2.corr()

In [6]:
cm = corr_matrix["confirmed_cases"].sort_values(ascending=False)
cm

confirmed_cases               1.000000
deaths                        0.782162
C_TOT_FEMALE                  0.631447
C_TOT_POP                     0.631154
C_TOT_MALE                    0.630692
                                ...
C_PCTPOV517_2019             -0.047248
C_PCTPOVALL_2019             -0.048445
C_PCTPOV017_2019             -0.052663
apple_mobility_driving       -0.074336
google_mobility_workplaces   -0.101761
Name: confirmed_cases, Length: 62, dtype: float64

In [7]:
cm.index[2]

'C_TOT_FEMALE'

In [8]:
cml = []
cl = []
for i in range(62):
    if cm[i] > 0.1 or cm[i]< 0.02:
        cml.append([cm.index[i],cm[i]])
        cl.append(cm.index[i])
cml,len(cl)

([['confirmed_cases', 1.0],
  ['deaths', 0.7821618715596683],
  ['C_TOT_FEMALE', 0.6314469799860544],
  ['C_TOT_POP', 0.6311542426332959],
  ['C_TOT_MALE', 0.6306923781724805],
  ['C_WA_MALE', 0.6240178805379313],
  ['C_WA_FEMALE', 0.6237192683317122],
  ['C_M_Labour_Force_corr', 0.48032895628711686],
  ['C_M_Employed_corr', 0.47332557857401186],
  ['total_adult_patients_hospitalized_confirmed_covid_SD', 0.2191026101523674],
  ['total_adult_patients_hospitalized_confirmed_and_suspected_covid_SD',
   0.2187183319228811],
  ['previous_day_admission_adult_covid_confirmed_SD', 0.21049320450532755],
  ['staffed_icu_adult_patients_confirmed_covid_SD', 0.19520946068263756],
  ['staffed_icu_adult_patients_confirmed_and_suspected_covid_SD',
   0.19273358858347478],
  ['staffed_adult_icu_bed_occupancy_SD', 0.19123968374327663],
  ['inpatient_beds_utilization_numerator_SD', 0.17620693907100857],
  ['inpatient_beds_utilization_denominator_SD', 0.1646764970981005],
  ['inpatient_beds_SD', 0.16021385445545092],
  ['total_pediatric_patients_hospitalized_confirmed_covid_SD',
   0.1564589380196173],
  ['staffed_adult_icu_bed_occupancy_coverage_SD', 0.15355084639863797],
  ['C_MinorityPCT', 0.15212662382922404],
  ['C_MEDHHINC_2019', 0.14473783535491666],
  ['adult_icu_bed_covid_utilization_SD', 0.14308292546197518],
  ['inpatient_bed_covid_utilization_SD', 0.14202817193887787],
  ['critical_staffing_shortage_anticipated_within_week_yes_SD',
   0.1415859941826538],
  ['critical_staffing_shortage_today_yes_SD', 0.14039404532832395],
  ['previous_day_admission_pediatric_covid_confirmed_SD', 0.13085884273283416],
  ['C_HispanicPCT', 0.12988433722778464],
  ['total_pediatric_patients_hospitalized_confirmed_and_suspected_covid_SD',
   0.12950712194755137],
  ['previous_day_admission_adult_covid_suspected_SD', 0.12365809876561364],
  ['percent_of_inpatients_with_covid_SD', 0.121138142966728],
  ['hospital_onset_covid_coverage_SD', 0.12000115587548586],
  ['inpatient_beds_coverage_SD', 0.11613468070531707],
  ['inpatient_beds_utilization_SD', 0.10858232378826796],
  ['Electricity_Sales_ Customers_Count_Industrial', 0.018435547299347127],
  ['hospital_onset_covid_SD', 0.015600740708162891],
  ['Electricity_Sales_ Sales_Industrial (MWHr)', 0.014803122717875934],
  ['countyFIPS', -0.0385892167468459],
  ['stateFIPS', -0.03859288614991974],
  ['C_PCTPOV517_2019', -0.047247795247234395],
  ['C_PCTPOVALL_2019', -0.048445215112370925],
  ['C_PCTPOV017_2019', -0.05266300898320347],
  ['apple_mobility_driving', -0.07433625181228463],
  ['google_mobility_workplaces', -0.10176132890436301]],
 44)

In [13]:
cl.remove('Electricity_Sales_ Customers_Count_Industrial')

In [14]:
val = pd.read_csv("EQ-2021-Validation-Data-Sample.csv")
val["confirmed_cases"] = x1["Confirmed_cases"]
val = val[cl]
val

,confirmed_cases,C_TOT_FEMALE,C_TOT_POP,C_TOT_MALE,C_WA_MALE,C_WA_FEMALE,C_M_Labour_Force_corr,C_M_Employed_corr,total_adult_patients_hospitalized_confirmed_covid_SD,total_adult_patients_hospitalized_confirmed_and_suspected_covid_SD,...,inpatient_beds_coverage_SD,inpatient_beds_utilization_SD,hospital_onset_covid_SD,countyFIPS,stateFIPS,C_PCTPOV517_2019,C_PCTPOVALL_2019,C_PCTPOV017_2019,apple_mobility_driving,google_mobility_workplaces
0,500.86,28461.0,55514.0,27053.0,21383.0,22185.0,25029.0,24237.0,1887,2027,...,110,0.745088,13,1001,1,14.4,12.1,15.9,144.74,-19.0
1,2016.47,97755.0,190790.0,93035.0,81423.0,85193.0,91638.0,88526.0,1887,2027,...,110,0.745088,13,1003,1,13.3,10.1,13.5,129.11,-22.0
2,191.88,12599.0,27201.0,14602.0,7397.0,6338.0,9629.0,9109.0,1887,2027,...,110,0.745088,13,1005,1,39.5,27.1,41.0,147.51,-16.0
3,117.84,10402.0,22597.0,12195.0,8903.0,8326.0,8539.0,8193.0,1887,2027,...,110,0.745088,13,1007,1,25.2,20.3,25.9,161.64,-19.0
4,462.46,29223.0,57826.0,28603.0,27498.0,28129.0,24585.0,24005.0,1887,2027,...,110,0.745088,13,1009,1,21.4,16.3,21.0,126.90,-23.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47125,57.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,44,...,30,0.367485,4,56037,56,NaN,NaN,NaN,111.02,-34.0
47126,109.51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,44,...,30,0.367485,4,56039,56,NaN,NaN,NaN,156.23,-30.0
47127,58.43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,44,...,30,0.367485,4,56041,56,NaN,NaN,NaN,118.07,-39.0
47128,58.42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,44,...,30,0.367485,4,56043,56,NaN,NaN,NaN,NaN,-40.0
47129,58.18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,44,...,30,0.367485,4,56045,56,NaN,NaN,NaN,NaN,-42.0

In [15]:
from sklearn.impute import SimpleImputer
mean_imputer = SimpleImputer(strategy="mean")

val_impt = mean_imputer.fit_transform(val)
val_impt

array([[ 5.00860000e+02,  2.84610000e+04,  5.55140000e+04, ...,
         1.59000000e+01,  1.44740000e+02, -1.90000000e+01],
       [ 2.01647000e+03,  9.77550000e+04,  1.90790000e+05, ...,
         1.35000000e+01,  1.29110000e+02, -2.20000000e+01],
       [ 1.91880000e+02,  1.25990000e+04,  2.72010000e+04, ...,
         4.10000000e+01,  1.47510000e+02, -1.60000000e+01],
       ...,
       [ 5.84300000e+01,  5.04432011e+04,  9.93366706e+04, ...,
         1.99670169e+01,  1.18070000e+02, -3.90000000e+01],
       [ 5.84200000e+01,  5.04432011e+04,  9.93366706e+04, ...,
         1.99670169e+01,  1.16470968e+02, -4.00000000e+01],
       [ 5.81800000e+01,  5.04432011e+04,  9.93366706e+04, ...,
         1.99670169e+01,  1.16470968e+02, -4.20000000e+01]])

In [16]:
Imp_val = pd.DataFrame(val_impt,columns=val.columns)
Imp_val

,confirmed_cases,C_TOT_FEMALE,C_TOT_POP,C_TOT_MALE,C_WA_MALE,C_WA_FEMALE,C_M_Labour_Force_corr,C_M_Employed_corr,total_adult_patients_hospitalized_confirmed_covid_SD,total_adult_patients_hospitalized_confirmed_and_suspected_covid_SD,...,inpatient_beds_coverage_SD,inpatient_beds_utilization_SD,hospital_onset_covid_SD,countyFIPS,stateFIPS,C_PCTPOV517_2019,C_PCTPOVALL_2019,C_PCTPOV017_2019,apple_mobility_driving,google_mobility_workplaces
0,500.86,28461.000000,55514.000000,27053.000000,21383.000000,22185.000000,25029.000000,24237.000000,1887.0,2027.0,...,110.0,0.745088,13.0,1001.0,1.0,14.400000,12.100000,15.900000,144.740000,-19.0
1,2016.47,97755.000000,190790.000000,93035.000000,81423.000000,85193.000000,91638.000000,88526.000000,1887.0,2027.0,...,110.0,0.745088,13.0,1003.0,1.0,13.300000,10.100000,13.500000,129.110000,-22.0
2,191.88,12599.000000,27201.000000,14602.000000,7397.000000,6338.000000,9629.000000,9109.000000,1887.0,2027.0,...,110.0,0.745088,13.0,1005.0,1.0,39.500000,27.100000,41.000000,147.510000,-16.0
3,117.84,10402.000000,22597.000000,12195.000000,8903.000000,8326.000000,8539.000000,8193.000000,1887.0,2027.0,...,110.0,0.745088,13.0,1007.0,1.0,25.200000,20.300000,25.900000,161.640000,-19.0
4,462.46,29223.000000,57826.000000,28603.000000,27498.000000,28129.000000,24585.000000,24005.000000,1887.0,2027.0,...,110.0,0.745088,13.0,1009.0,1.0,21.400000,16.300000,21.000000,126.900000,-23.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47125,57.50,50443.201085,99336.670603,48893.469518,38332.307054,39043.500479,50944.461318,47632.238777,37.0,44.0,...,30.0,0.367485,4.0,56037.0,56.0,18.733843,14.455333,19.967017,111.020000,-34.0
47126,109.51,50443.201085,99336.670603,48893.469518,38332.307054,39043.500479,50944.461318,47632.238777,37.0,44.0,...,30.0,0.367485,4.0,56039.0,56.0,18.733843,14.455333,19.967017,156.230000,-30.0
47127,58.43,50443.201085,99336.670603,48893.469518,38332.307054,39043.500479,50944.461318,47632.238777,37.0,44.0,...,30.0,0.367485,4.0,56041.0,56.0,18.733843,14.455333,19.967017,118.070000,-39.0
47128,58.42,50443.201085,99336.670603,48893.469518,38332.307054,39043.500479,50944.461318,47632.238777,37.0,44.0,...,30.0,0.367485,4.0,56043.0,56.0,18.733843,14.455333,19.967017,116.470968,-40.0
47129,58.18,50443.201085,99336.670603,48893.469518,38332.307054,39043.500479,50944.461318,47632.238777,37.0,44.0,...,30.0,0.367485,4.0,56045.0,56.0,18.733843,14.455333,19.967017,116.470968,-42.0

In [17]:
Imp_val.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47130 entries, 0 to 47129
Data columns (total 41 columns):
 #   Column                                                                  Non-Null Count  Dtype
---  ------                                                                  --------------  -----
 0   confirmed_cases                                                         47130 non-null  float64
 1   C_TOT_FEMALE                                                            47130 non-null  float64
 2   C_TOT_POP                                                               47130 non-null  float64
 3   C_TOT_MALE                                                              47130 non-null  float64
 4   C_WA_MALE                                                               47130 non-null  float64
 5   C_WA_FEMALE                                                             47130 non-null  float64
 6   C_M_Labour_Force_corr                                                   47130 non-null  float64
 7   C_M_Employed_corr                                                       47130 non-null  float64
 8   total_adult_patients_hospitalized_confirmed_covid_SD                    47130 non-null  float64
 9   total_adult_patients_hospitalized_confirmed_and_suspected_covid_SD      47130 non-null  float64
 10  previous_day_admission_adult_covid_confirmed_SD                         47130 non-null  float64
 11  staffed_icu_adult_patients_confirmed_covid_SD                           47130 non-null  float64
 12  staffed_icu_adult_patients_confirmed_and_suspected_covid_SD             47130 non-null  float64
 13  staffed_adult_icu_bed_occupancy_SD                                      47130 non-null  float64
 14  inpatient_beds_utilization_numerator_SD                                 47130 non-null  float64
 15  inpatient_beds_utilization_denominator_SD                               47130 non-null  float64
 16  inpatient_beds_SD                                                       47130 non-null  float64
 17  total_pediatric_patients_hospitalized_confirmed_covid_SD                47130 non-null  float64
 18  staffed_adult_icu_bed_occupancy_coverage_SD                             47130 non-null  float64
 19  C_MinorityPCT                                                           47130 non-null  float64
 20  C_MEDHHINC_2019                                                         47130 non-null  float64
 21  adult_icu_bed_covid_utilization_SD                                      47130 non-null  float64
 22  inpatient_bed_covid_utilization_SD                                      47130 non-null  float64
 23  critical_staffing_shortage_anticipated_within_week_yes_SD               47130 non-null  float64
 24  critical_staffing_shortage_today_yes_SD                                 47130 non-null  float64
 25  previous_day_admission_pediatric_covid_confirmed_SD                     47130 non-null  float64
 26  C_HispanicPCT                                                           47130 non-null  float64
 27  total_pediatric_patients_hospitalized_confirmed_and_suspected_covid_SD  47130 non-null  float64
 28  previous_day_admission_adult_covid_suspected_SD                         47130 non-null  float64
 29  percent_of_inpatients_with_covid_SD                                     47130 non-null  float64
 30  hospital_onset_covid_coverage_SD                                        47130 non-null  float64
 31  inpatient_beds_coverage_SD                                              47130 non-null  float64
 32  inpatient_beds_utilization_SD                                           47130 non-null  float64
 33  hospital_onset_covid_SD                                                 47130 non-null  float64
 34  countyFIPS                                                              47130 non-null  float64
 35  stateFIPS                                                               47130 non-null  float64
 36  C_PCTPOV517_2019                                                        47130 non-null  float64
 37  C_PCTPOVALL_2019                                                        47130 non-null  float64
 38  C_PCTPOV017_2019                                                        47130 non-null  float64
 39  apple_mobility_driving                                                  47130 non-null  float64
 40  google_mobility_workplaces                                              47130 non-null  float64
dtypes: float64(41)
memory usage: 14.7 MB

In [18]:
x2= x2[cl]
x2

,confirmed_cases,C_TOT_FEMALE,C_TOT_POP,C_TOT_MALE,C_WA_MALE,C_WA_FEMALE,C_M_Labour_Force_corr,C_M_Employed_corr,total_adult_patients_hospitalized_confirmed_covid_SD,total_adult_patients_hospitalized_confirmed_and_suspected_covid_SD,...,inpatient_beds_coverage_SD,inpatient_beds_utilization_SD,hospital_onset_covid_SD,countyFIPS,stateFIPS,C_PCTPOV517_2019,C_PCTPOVALL_2019,C_PCTPOV017_2019,apple_mobility_driving,google_mobility_workplaces
0,0.0,28461.0,55514.0,27053.0,21383.0,22185.0,26127.000000,25513.000000,0.0,0.0,...,1.0,0.000000,0.0,1001.0,1.0,14.4,12.1,15.9,101.510000,-23.15808
1,0.0,97755.0,190790.0,93035.0,81423.0,85193.0,95993.000000,93689.000000,0.0,0.0,...,1.0,0.000000,0.0,1003.0,1.0,13.3,10.1,13.5,103.120000,-23.15808
2,0.0,12599.0,27201.0,14602.0,7397.0,6338.0,8624.000000,8349.000000,0.0,0.0,...,1.0,0.000000,0.0,1005.0,1.0,39.5,27.1,41.0,120.670000,-23.15808
3,0.0,10402.0,22597.0,12195.0,8903.0,8326.0,8752.000000,8534.000000,0.0,0.0,...,1.0,0.000000,0.0,1007.0,1.0,25.2,20.3,25.9,111.180000,-23.15808
4,0.0,29223.0,57826.0,28603.0,27498.0,28129.0,25508.000000,24930.000000,0.0,0.0,...,1.0,0.000000,0.0,1009.0,1.0,21.4,16.3,21.0,91.560000,-23.15808
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1179370,3472.0,21652.0,45267.0,23615.0,22314.0,20480.0,51216.996241,47079.516243,52.0,62.0,...,31.0,0.417532,6.0,56037.0,56.0,8.2,8.3,10.1,161.130000,-23.15808
1179371,3078.0,10330.0,21675.0,11345.0,10841.0,9813.0,51216.996241,47079.516243,52.0,62.0,...,31.0,0.417532,6.0,56039.0,56.0,4.7,6.0,5.7,171.600000,-23.15808
1179372,1960.0,10380.0,21025.0,10645.0,10212.0,9980.0,51216.996241,47079.516243,52.0,62.0,...,31.0,0.417532,6.0,56041.0,56.0,7.8,8.5,9.6,148.020000,-23.15808
1179373,864.0,4215.0,8464.0,4249.0,4060.0,4009.0,51216.996241,47079.516243,52.0,62.0,...,31.0,0.417532,6.0,56043.0,56.0,12.3,11.1,13.9,142.338662,-23.15808
1179374,610.0,3354.0,7082.0,3728.0,3553.0,3205.0,51216.996241,47079.516243,52.0,62.0,...,31.0,0.417532,6.0,56045.0,56.0,11.8,10.5,13.8,142.338662,-23.15808

In [25]:
Tab_df = pd.concat([x2,Imp_val],axis=0)
Tab_df

,confirmed_cases,C_TOT_FEMALE,C_TOT_POP,C_TOT_MALE,C_WA_MALE,C_WA_FEMALE,C_M_Labour_Force_corr,C_M_Employed_corr,total_adult_patients_hospitalized_confirmed_covid_SD,total_adult_patients_hospitalized_confirmed_and_suspected_covid_SD,...,inpatient_beds_coverage_SD,inpatient_beds_utilization_SD,hospital_onset_covid_SD,countyFIPS,stateFIPS,C_PCTPOV517_2019,C_PCTPOVALL_2019,C_PCTPOV017_2019,apple_mobility_driving,google_mobility_workplaces
0,0.00,28461.000000,55514.000000,27053.000000,21383.000000,22185.000000,26127.000000,25513.000000,0.0,0.0,...,1.0,0.000000,0.0,1001.0,1.0,14.400000,12.100000,15.900000,101.510000,-23.15808
1,0.00,97755.000000,190790.000000,93035.000000,81423.000000,85193.000000,95993.000000,93689.000000,0.0,0.0,...,1.0,0.000000,0.0,1003.0,1.0,13.300000,10.100000,13.500000,103.120000,-23.15808
2,0.00,12599.000000,27201.000000,14602.000000,7397.000000,6338.000000,8624.000000,8349.000000,0.0,0.0,...,1.0,0.000000,0.0,1005.0,1.0,39.500000,27.100000,41.000000,120.670000,-23.15808
3,0.00,10402.000000,22597.000000,12195.000000,8903.000000,8326.000000,8752.000000,8534.000000,0.0,0.0,...,1.0,0.000000,0.0,1007.0,1.0,25.200000,20.300000,25.900000,111.180000,-23.15808
4,0.00,29223.000000,57826.000000,28603.000000,27498.000000,28129.000000,25508.000000,24930.000000,0.0,0.0,...,1.0,0.000000,0.0,1009.0,1.0,21.400000,16.300000,21.000000,91.560000,-23.15808
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47125,57.50,50443.201085,99336.670603,48893.469518,38332.307054,39043.500479,50944.461318,47632.238777,37.0,44.0,...,30.0,0.367485,4.0,56037.0,56.0,18.733843,14.455333,19.967017,111.020000,-34.00000
47126,109.51,50443.201085,99336.670603,48893.469518,38332.307054,39043.500479,50944.461318,47632.238777,37.0,44.0,...,30.0,0.367485,4.0,56039.0,56.0,18.733843,14.455333,19.967017,156.230000,-30.00000
47127,58.43,50443.201085,99336.670603,48893.469518,38332.307054,39043.500479,50944.461318,47632.238777,37.0,44.0,...,30.0,0.367485,4.0,56041.0,56.0,18.733843,14.455333,19.967017,118.070000,-39.00000
47128,58.42,50443.201085,99336.670603,48893.469518,38332.307054,39043.500479,50944.461318,47632.238777,37.0,44.0,...,30.0,0.367485,4.0,56043.0,56.0,18.733843,14.455333,19.967017,116.470968,-40.00000
47129,58.18,50443.201085,99336.670603,48893.469518,38332.307054,39043.500479,50944.461318,47632.238777,37.0,44.0,...,30.0,0.367485,4.0,56045.0,56.0,18.733843,14.455333,19.967017,116.470968,-42.00000

In [26]:
Tab_df.to_csv("Tab_vis_time_2.csv",index=False)

## Load and Resume

In [4]:
x1 = pd.read_csv("MeanImputedNotScaled_dated.csv")
x1

,DOMESTIC_Flights_Cnt,INTERNATIONAL_Flights_Cnt,INTERNATIONAL_Air_Passengers,DOMESTIC_Air_Passengers,apple_mobility_driving,google_mobility_workplaces,Electricity_Sales_ Customers_Count_Transportation,Electricity_Sales_ Customers_Count_Industrial,Electricity_Sales_ Revenue_Transportation ($ x1000),Electricity_Sales_ Sales_Transportation (MWHr),...,C_HispanicPCT,C_PCTPOVALL_2019,C_PCTPOV017_2019,C_PCTPOV517_2019,C_MEDHHINC_2019,deaths,stateFIPS,confirmed_cases,countyFIPS,date
0,10925.018692,682.528037,50595.607477,588759.504673,101.510000,-23.15808,0.000000,16298.000000,0.000000,0.000000,...,0.0257,12.1,15.9,14.4,58233.0,0.0,1.0,0.0,1001.0,2020-01-22
1,10925.018692,682.528037,50595.607477,588759.504673,103.120000,-23.15808,0.000000,16298.000000,0.000000,0.000000,...,0.0458,10.1,13.5,13.3,59871.0,0.0,1.0,0.0,1003.0,2020-01-22
2,10925.018692,682.528037,50595.607477,588759.504673,120.670000,-23.15808,0.000000,16298.000000,0.000000,0.000000,...,0.0509,27.1,41.0,39.5,35972.0,0.0,1.0,0.0,1005.0,2020-01-22
3,10925.018692,682.528037,50595.607477,588759.504673,111.180000,-23.15808,0.000000,16298.000000,0.000000,0.000000,...,0.0204,20.3,25.9,25.2,47918.0,0.0,1.0,0.0,1007.0,2020-01-22
4,10925.018692,682.528037,50595.607477,588759.504673,91.560000,-23.15808,0.000000,16298.000000,0.000000,0.000000,...,0.0860,16.3,21.0,21.4,52902.0,0.0,1.0,0.0,1009.0,2020-01-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1179370,10925.018692,682.528037,50595.607477,588759.504673,161.130000,-23.15808,3.231321,72386.890999,2019.507886,21366.056357,...,0.1584,8.3,10.1,8.2,80639.0,32.0,56.0,3472.0,56037.0,2021-01-30
1179371,10925.018692,682.528037,50595.607477,588759.504673,171.600000,-23.15808,3.231321,72386.890999,2019.507886,21366.056357,...,0.1560,6.0,5.7,4.7,98837.0,6.0,56.0,3078.0,56039.0,2021-01-30
1179372,10925.018692,682.528037,50595.607477,588759.504673,148.020000,-23.15808,3.231321,72386.890999,2019.507886,21366.056357,...,0.0906,8.5,9.6,7.8,70756.0,12.0,56.0,1960.0,56041.0,2021-01-30
1179373,10925.018692,682.528037,50595.607477,588759.504673,142.338662,-23.15808,3.231321,72386.890999,2019.507886,21366.056357,...,0.1400,11.1,13.9,12.3,55122.0,25.0,56.0,864.0,56043.0,2021-01-30
1179374,10925.018692,682.528037,50595.607477,588759.504673,142.338662,-23.15808,3.231321,72386.890999,2019.507886,21366.056357,...,0.0361,10.5,13.8,11.8,59410.0,4.0,56.0,610.0,56045.0,2021-01-30

In [5]:
col_list = x1.columns.to_list()
col_list

['DOMESTIC_Flights_Cnt',
 'INTERNATIONAL_Flights_Cnt',
 'INTERNATIONAL_Air_Passengers',
 'DOMESTIC_Air_Passengers',
 'apple_mobility_driving',
 'google_mobility_workplaces',
 'Electricity_Sales_ Customers_Count_Transportation',
 'Electricity_Sales_ Customers_Count_Industrial',
 'Electricity_Sales_ Revenue_Transportation ($ x1000)',
 'Electricity_Sales_ Sales_Transportation (MWHr)',
 'Electricity_Sales_ Customers_Count_Residential',
 'Electricity_Sales_ Revenue_Commercial ($ x1000)',
 'Electricity_Sales_ Customers_Count_Commercial',
 'Electricity_Sales_ Sales_Commercial (MWHr)',
 'Electricity_Sales_ Revenue_Residential ($ x1000)',
 'Electricity_Sales_ Sales_Residential (MWHr)',
 'Electricity_Sales_ Sales_Industrial (MWHr)',
 'Electricity_Sales_ Revenue_Industrial ($ x1000)',
 'previous_day_admission_pediatric_covid_suspected_SD',
 'staffed_adult_icu_bed_occupancy_SD',
 'inpatient_bed_covid_utilization_SD',
 'percent_of_inpatients_with_covid_SD',
 'inpatient_beds_utilization_denominator_SD',
 'inpatient_beds_utilization_numerator_SD',
 'inpatient_beds_utilization_SD',
 'total_pediatric_patients_hospitalized_confirmed_covid_SD',
 'total_pediatric_patients_hospitalized_confirmed_and_suspected_covid_SD',
 'total_adult_patients_hospitalized_confirmed_covid_SD',
 'total_adult_patients_hospitalized_confirmed_and_suspected_covid_SD',
 'staffed_icu_adult_patients_confirmed_covid_SD',
 'staffed_icu_adult_patients_confirmed_and_suspected_covid_SD',
 'staffed_adult_icu_bed_occupancy_coverage_SD',
 'adult_icu_bed_utilization_SD',
 'previous_day_admission_pediatric_covid_confirmed_SD',
 'previous_day_admission_adult_covid_suspected_SD',
 'previous_day_admission_adult_covid_confirmed_SD',
 'inpatient_beds_coverage_SD',
 'adult_icu_bed_covid_utilization_SD',
 'inpatient_beds_SD',
 'hospital_onset_covid_coverage_SD',
 'hospital_onset_covid_SD',
 'critical_staffing_shortage_anticipated_within_week_yes_SD',
 'critical_staffing_shortage_today_yes_SD',
 'C_M_Employed_corr',
 'C_M_Labour_Force_corr',
 'C_M_Unemployment_Rate_corr',
 'C_TOT_MALE',
 'C_WA_MALE',
 'C_TOT_POP',
 'C_TOT_FEMALE',
 'C_WA_FEMALE',
 'C_MinorityPCT',
 'C_BlackPCT',
 'C_HispanicPCT',
 'C_PCTPOVALL_2019',
 'C_PCTPOV017_2019',
 'C_PCTPOV517_2019',
 'C_MEDHHINC_2019',
 'deaths',
 'stateFIPS',
 'confirmed_cases',
 'countyFIPS',
 'date']

In [ ]:
fig = plt.figure()
ax = fig.add_axes([0,0,1,1])
x = np.array(x1["stateFIPS"])
y = np.array(x1["confirmed_cases"])
ax.bar(x,y)
plt.show()

In [16]:
np.array(x1["stateFIPS"])

array([ 1.,  1.,  1., ..., 56., 56., 56.])

## Inserting date

In [3]:
a = pd.read_csv("tab_vis_3.csv")
a

,confirmed_cases,C_TOT_FEMALE,C_TOT_POP,C_TOT_MALE,C_WA_MALE,C_WA_FEMALE,C_M_Labour_Force_corr,C_M_Employed_corr,total_adult_patients_hospitalized_confirmed_covid_SD,total_adult_patients_hospitalized_confirmed_and_suspected_covid_SD,...,inpatient_beds_utilization_SD,hospital_onset_covid_SD,countyFIPS,stateFIPS,C_PCTPOV517_2019,C_PCTPOVALL_2019,C_PCTPOV017_2019,apple_mobility_driving,google_mobility_workplaces,date
0,0.00,28461.000000,55514.000000,27053.000000,21383.000000,22185.000000,26127.000000,25513.000000,0.0,0.0,...,0.000000,0.0,1001.0,1.0,14.400000,12.100000,15.900000,101.510000,-23.15808,2020-01-22
1,0.00,97755.000000,190790.000000,93035.000000,81423.000000,85193.000000,95993.000000,93689.000000,0.0,0.0,...,0.000000,0.0,1003.0,1.0,13.300000,10.100000,13.500000,103.120000,-23.15808,2020-01-22
2,0.00,12599.000000,27201.000000,14602.000000,7397.000000,6338.000000,8624.000000,8349.000000,0.0,0.0,...,0.000000,0.0,1005.0,1.0,39.500000,27.100000,41.000000,120.670000,-23.15808,2020-01-22
3,0.00,10402.000000,22597.000000,12195.000000,8903.000000,8326.000000,8752.000000,8534.000000,0.0,0.0,...,0.000000,0.0,1007.0,1.0,25.200000,20.300000,25.900000,111.180000,-23.15808,2020-01-22
4,0.00,29223.000000,57826.000000,28603.000000,27498.000000,28129.000000,25508.000000,24930.000000,0.0,0.0,...,0.000000,0.0,1009.0,1.0,21.400000,16.300000,21.000000,91.560000,-23.15808,2020-01-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1226500,57.50,50443.201085,99336.670603,48893.469518,38332.307054,39043.500479,50944.461318,47632.238777,37.0,44.0,...,0.367485,4.0,56037.0,56.0,18.733843,14.455333,19.967017,111.020000,-34.00000,15-02-2021
1226501,109.51,50443.201085,99336.670603,48893.469518,38332.307054,39043.500479,50944.461318,47632.238777,37.0,44.0,...,0.367485,4.0,56039.0,56.0,18.733843,14.455333,19.967017,156.230000,-30.00000,15-02-2021
1226502,58.43,50443.201085,99336.670603,48893.469518,38332.307054,39043.500479,50944.461318,47632.238777,37.0,44.0,...,0.367485,4.0,56041.0,56.0,18.733843,14.455333,19.967017,118.070000,-39.00000,15-02-2021
1226503,58.42,50443.201085,99336.670603,48893.469518,38332.307054,39043.500479,50944.461318,47632.238777,37.0,44.0,...,0.367485,4.0,56043.0,56.0,18.733843,14.455333,19.967017,116.470968,-40.00000,15-02-2021
1226504,58.18,50443.201085,99336.670603,48893.469518,38332.307054,39043.500479,50944.461318,47632.238777,37.0,44.0,...,0.367485,4.0,56045.0,56.0,18.733843,14.455333,19.967017,116.470968,-42.00000,15-02-2021

In [4]:
a["C_TOT_POP"].isnull().sum()

0

In [6]:
b = pd.read_csv("Tab_vis_time_2.csv")
b["date"] = a["date"]
b

,confirmed_cases,C_TOT_FEMALE,C_TOT_POP,C_TOT_MALE,C_WA_MALE,C_WA_FEMALE,C_M_Labour_Force_corr,C_M_Employed_corr,total_adult_patients_hospitalized_confirmed_covid_SD,total_adult_patients_hospitalized_confirmed_and_suspected_covid_SD,...,inpatient_beds_utilization_SD,hospital_onset_covid_SD,countyFIPS,stateFIPS,C_PCTPOV517_2019,C_PCTPOVALL_2019,C_PCTPOV017_2019,apple_mobility_driving,google_mobility_workplaces,date
0,0.00,28461.000000,55514.000000,27053.000000,21383.000000,22185.000000,26127.000000,25513.000000,0.0,0.0,...,0.000000,0.0,1001.0,1.0,14.400000,12.100000,15.900000,101.510000,-23.15808,2020-01-22
1,0.00,97755.000000,190790.000000,93035.000000,81423.000000,85193.000000,95993.000000,93689.000000,0.0,0.0,...,0.000000,0.0,1003.0,1.0,13.300000,10.100000,13.500000,103.120000,-23.15808,2020-01-22
2,0.00,12599.000000,27201.000000,14602.000000,7397.000000,6338.000000,8624.000000,8349.000000,0.0,0.0,...,0.000000,0.0,1005.0,1.0,39.500000,27.100000,41.000000,120.670000,-23.15808,2020-01-22
3,0.00,10402.000000,22597.000000,12195.000000,8903.000000,8326.000000,8752.000000,8534.000000,0.0,0.0,...,0.000000,0.0,1007.0,1.0,25.200000,20.300000,25.900000,111.180000,-23.15808,2020-01-22
4,0.00,29223.000000,57826.000000,28603.000000,27498.000000,28129.000000,25508.000000,24930.000000,0.0,0.0,...,0.000000,0.0,1009.0,1.0,21.400000,16.300000,21.000000,91.560000,-23.15808,2020-01-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1226500,57.50,50443.201085,99336.670603,48893.469518,38332.307054,39043.500479,50944.461318,47632.238777,37.0,44.0,...,0.367485,4.0,56037.0,56.0,18.733843,14.455333,19.967017,111.020000,-34.00000,15-02-2021
1226501,109.51,50443.201085,99336.670603,48893.469518,38332.307054,39043.500479,50944.461318,47632.238777,37.0,44.0,...,0.367485,4.0,56039.0,56.0,18.733843,14.455333,19.967017,156.230000,-30.00000,15-02-2021
1226502,58.43,50443.201085,99336.670603,48893.469518,38332.307054,39043.500479,50944.461318,47632.238777,37.0,44.0,...,0.367485,4.0,56041.0,56.0,18.733843,14.455333,19.967017,118.070000,-39.00000,15-02-2021
1226503,58.42,50443.201085,99336.670603,48893.469518,38332.307054,39043.500479,50944.461318,47632.238777,37.0,44.0,...,0.367485,4.0,56043.0,56.0,18.733843,14.455333,19.967017,116.470968,-40.00000,15-02-2021
1226504,58.18,50443.201085,99336.670603,48893.469518,38332.307054,39043.500479,50944.461318,47632.238777,37.0,44.0,...,0.367485,4.0,56045.0,56.0,18.733843,14.455333,19.967017,116.470968,-42.00000,15-02-2021

In [7]:
b["date"]

0          2020-01-22
1          2020-01-22
2          2020-01-22
3          2020-01-22
4          2020-01-22
              ...
1226500    15-02-2021
1226501    15-02-2021
1226502    15-02-2021
1226503    15-02-2021
1226504    15-02-2021
Name: date, Length: 1226505, dtype: object

In [8]:
#b.to_csv("tab_vis_3.csv",index=False)